/** ISO 3166-1 alpha-2 codes with English labels — common Middle East & North Africa set for clinic forms. */
export const MIDDLE_EAST_COUNTRY_OPTIONS: { value: string; label: string }[] = [
  { value: "AE", label: "United Arab Emirates" },
  { value: "BH", label: "Bahrain" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "KW", label: "Kuwait" },
  { value: "QA", label: "Qatar" },
  { value: "OM", label: "Oman" },
  { value: "YE", label: "Yemen" },
  { value: "IQ", label: "Iraq" },
  { value: "IR", label: "Iran" },
  { value: "JO", label: "Jordan" },
  { value: "LB", label: "Lebanon" },
  { value: "SY", label: "Syria" },
  { value: "PS", label: "Palestine" },
  { value: "IL", label: "Israel" },
  { value: "TR", label: "Turkey" },
  { value: "EG", label: "Egypt" },
  { value: "CY", label: "Cyprus" },
  { value: "LY", label: "Libya" },
  { value: "TN", label: "Tunisia" },
  { value: "DZ", label: "Algeria" },
  { value: "MA", label: "Morocco" },
  { value: "SD", label: "Sudan" },
  { value: "DJ", label: "Djibouti" },
  { value: "SO", label: "Somalia" },
];
